services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel
    restart: unless-stopped
    volumes:
      - ./laravel:/var/www/html
    networks:
      - laravel
    depends_on:
      - mysql
  react:
    build:
      context: ./react
    container_name: react
    ports:
      - "5173:5173"
    restart: unless-stopped
    volumes:
      - ./react:/app
    #  - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    networks:
      - laravel

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./laravel:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - laravel
    depends_on:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mobile
      MYSQL_USER: admin  
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
